Adding C FFI to rust prio lib and python implementations
abetterinternet/libprio-rs pull request #1
Opened 2020-08-06 19:58 UTC by winstrom

2020-09-14 18:03 UTC, tgeoghegan commented
@winstrom: This change is generally useful, but I think I'm missing some context: is there a plan for some client out there to use either the C or Python bindings here or is this mainly useful so folks can experiment with this library without needing to get up to speed on Rust?

2020-09-14 18:41 UTC, winstrom commented
> @winstrom: This change is generally useful, but I think I'm missing some context: is there a plan for some client out there to use either the C or Python bindings here or is this mainly useful so folks can experiment with this library without needing to get up to speed on Rust?

This is a quick and dirty implementation so that people can get up to speed on the data flow and test that packets serialized on devices are able to be properly aggregated.  This is not meant as a production implementation.

This also allows for experimentation in a python framework which may allow for faster iteration than in Rust.  E.g. for different serialization strategies.

2020-09-15 16:17 UTC, tgeoghegan commented
Thanks for that context, Luke. My concern is that this stuff doesn't have any tests on it and we won't use this stuff in prod, so we can't be sure that changes we make to libprio_rs in the future won't break the Python bindings or the notebooks built on them. If we put something in a public repo we own, the implication is that we own that code and attest to its functionality. But clearly this stuff is useful because folks at several partners have been using these Jupyter notebooks, so we should have them somewhere that's easy to access, though longer term I don't think we should have this code in this repo if we don't really plan to support it.

2020-09-15 16:46 UTC, winstrom commented
I'd be fine with this in an "experimental" or some other such branch.  Or in a different repo expressly for the purpose of demonstration.

2020-09-16 21:47 UTC, yuriks requested changes
Sorry for how long it took to get this done. I think it's definitely valuable to have a C API for the library, and this is a starting point for that. While I think I did find a bug in some of the Python library definitions, most of the comments are about structure and organization of the code.

The Rust and Python code had several formatting issues, but I didn't point them out explicitly. Rather I'd recommend running `rustfmt` on the files to make sure they follow the usual Rust standards. I don't think we have a preferred formatting tool for Python, so if you have any particular preferences for that it's probably fine to just use that for now and we can standardize on something later.

Apart from the comments in specific files, I think we should have a better separation in terms of what's an API and what's example code, especially on the Python side. On the Rust code I think we should move all of the FFI-related modules into a submodule so that they're separate from the rest of the code implementing the algorithm. Similarly on the Python side, I think keeping the function wrappers and the rest of the code+ipy notebook would be useful.

I wasn't really able to test the Python notebook, but I checked that the Rust part of it at least builds, though it needs some modifications aroudn the crate setup for that. To make this work as an `.so`, the library type needs to be set to `cdylib` in `Cargo.toml`. However, given that this is going to be a dual Rust-C library, we probably want the C compilation target to be a separate library in a subdirectory, so that both can be built as needed.

 We should probably add some tests in the future to make sure the interfaces all work correctly when called.

I know we're all busy, so, instead of going back on forth on comments in this review, if you'd like instead I can just apply my suggestions to the PR, either on a separate commit or rebasing yours, so you don't have to spent time following up on it. Let me know if you'd prefer that.

2020-09-16 21:47 UTC, yuriks commented on src/c_vec.rs
> +extern crate libc;
External crates should only ever be declared in the root module of the library, and added to the Cargo manifest so they're pulled in as a dependency when necessary.

2020-09-17 02:58 UTC, winstrom commented
Yuri,

Thank you for such a great and in depth review.  I think you're spot on with the edits.  Please do just apply them.  And if it's better to create a new repo for the FFI stuff and experiments, that sounds good to me.  Please go ahead and fix all my mistakes ;).

2020-09-28 20:57 UTC, yuriks commented
Just to clarify status: I started cleaning up the branch locally, but setting up the build system for the Python stuff turned out to be quite time-consuming, so I paused this for now in lieu of working on the prio-server code for a while. I'll pick this back up in the future when I have some time.

2020-09-28 21:21 UTC, winstrom commented
Sounds good to me.  I agree concentrating on server is more important.

2021-09-20 19:42 UTC, tgeoghegan commented
It's not clear that we want to commit to maintaining a Python interface to crate `prio`, and if we ever did we'd probably make one that exposes the PCP or PPM interfaces rather than the Prio v2 stuff, so I'm going to close this PR.

2021-09-20 19:42 UTC, closed without merging