pcp::types: Specialize `PolyCheckedVector` into `Sum` type
abetterinternet/libprio-rs pull request #111
Opened 2021-11-01 16:07 UTC by cjpatton

Based on #110.
Partially closes #94.

2021-11-01 20:26 UTC, tgeoghegan requested changes
I think my question here is related to my questions on #109.

2021-11-01 20:26 UTC, tgeoghegan commented on src/pcp/types.rs
> +            data.push(w);
IIUC, we'll end up encoding a single `Field126` value as 128 `Field126` values, each of which is 0 or 1. Why not represent it as a single `Field126`, and use `poly_range_check(0, Field126::MAX)` as `range_checker`? Or use some caller provided upper bound (perhaps they know something about the data they're recording that lets them provide a tighter upper bound).

2021-11-02 00:37 UTC, tgeoghegan commented on src/pcp/types.rs
> +            data.push(w);
OK, that all makes sense. I have no other comments on this PR, but we should resolve #109 so I'll refrain from approving this for now.

2021-11-02 00:59 UTC, tgeoghegan approved these changes

2021-11-02 18:42 UTC, cjpatton commented
Removed `PolyCheckedVector` benchmark.

2021-11-02 18:49 UTC, merged