prio3: Serialize `Prio3VerifyParam`
abetterinternet/libprio-rs pull request #192
Opened 2022-03-08 00:55 UTC by cjpatton

Based on #191 (merge that first).

Adds serialization for Prio3 verification parameter.

2022-03-08 02:07 UTC, tgeoghegan requested changes
I had also been thinking that we will need this so that the two aggregators can share verify params in a deployment where they're not in the same process. However I think we need to express this in `trait Vdaf`, which is to say, some trait bound on the `Vdaf::VerifyParam`, so that PPM implementations can do this generically for any VDAF.

2022-03-09 01:18 UTC, cjpatton commented
This is also an encoding that's not specified in the VDAF draft.** How about following this suggestion https://github.com/abetterinternet/libprio-rs/pull/195#pullrequestreview-903742114 here as well? I.e., don't bound the trait, but provide the implementation where needed? In particular I could implement serialization for Poplar1 in this PR as well, if you like.

** I can see an argument for having the draft specify this encoding. If you want to advocate for this, then let's open an issue here: https://github.com/cjpatton/vdaf/issues

2022-03-09 19:25 UTC, cjpatton commented
Issue raised: https://github.com/cjpatton/vdaf/issues/38

The format we chose here is quite simple and could easily be adopted in the VDAF draft. In TLS-syntax:

```
struct {
   opaque k_query_init[Prg.SEED_SIZE];
   uint8_t aggregator_id;
} Prio3VerifyParam;
```

We'd have a similar format for Poplar1:

```
struct {
   opaque k_query_init[Prg.SEED_SIZE];
   uint8_t is_leader; // boolean indicating whether the aggregator is the leader
} Poplar1VerifyParam;
```

@tgeoghegan let me know if this PR needs changes. I'm happy to provide an implementation for Poplar1 as well.

2022-03-09 21:23 UTC, tgeoghegan commented
This looks good for `prio3`! But yes, let's wire it up for `poplar1`, too.

2022-03-09 21:24 UTC, tgeoghegan requested changes
This looks good for `prio3`! But yes, let's wire it up for `poplar1`, too.

2022-03-09 21:53 UTC, cjpatton commented
Done.

2022-03-09 22:05 UTC, divergentdave commented on src/vdaf/poplar1.rs
> +    /// Length of the IPDF input.
```suggestion
    /// Length of the IDPF input.
```

2022-03-09 22:07 UTC, cjpatton commented on src/vdaf/poplar1.rs
> +    /// Length of the IPDF input.
Ugh, my dyslexia ...

2022-03-09 22:34 UTC, tgeoghegan approved these changes

2022-03-09 22:35 UTC, merged